services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3003:3003"
    depends_on:
      - backend
    networks:
      - mdt-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "14552-14559:14552-14559/udp"
      - "15000-15009:15000-15009/udp"
    volumes:
      - ./logs:/app/logs
    networks:
      - mdt-network

  backend1:
    build:
      context: ./Backend1
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
      - "8080:8080"
    networks:
      - mdt-network

networks:
  mdt-network:
    driver: bridge
